# Generated by Django 4.2.3 on 2023-07-21 01:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('site_escola', '0003_remove_task_school_subjects'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizOptions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='schoolsubjects',
            name='classroom',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='schoolsubjects',
        ),
        migrations.RenameModel(
            old_name='Task',
            new_name='Quiz',
        ),
        migrations.DeleteModel(
            name='Aluno',
        ),
        migrations.DeleteModel(
            name='Classroom',
        ),
        migrations.DeleteModel(
            name='SchoolSubjects',
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
        migrations.AddField(
            model_name='quizoptions',
            name='from_quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='site_escola.quiz'),
        ),
    ]
