# Generated by Django 4.2.3 on 2023-07-23 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_escola', '0005_remove_quizoptions_from_quiz_quizquestion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizquestion',
            name='from_quiz',
        ),
    ]
