# Generated by Django 4.2.3 on 2023-07-23 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_escola', '0007_quizquestion_from_quiz'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizquestion',
            name='n_options',
            field=models.IntegerField(null=True),
        ),
    ]
