# Generated by Django 4.2.3 on 2023-07-23 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_escola', '0011_alter_quizquestion_n_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizquestion',
            name='n_options',
            field=models.IntegerField(default=1, null=True),
        ),
    ]
